DjWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls', namespace='music')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # music/

    path('<int:pk>/', views.RetrieveView.as_view(), name='retrieve'),  # /music/<album_id>/

    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),  # /music/album/add/

    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),  # /music/album/#/

    path('album/<int:pk>/delete', views.AlbumDelete.as_view(), name='album-delete'),  # /music/album/#/delete

    path('register/', views.UserFormView.as_view(), name='register'),

    path('login_user/', views.login_user, name='login_user'),

    path('logout_user/', views.logout_user, name='logout_user'),

]

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Albums(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)  # current user
    name = models.CharField(max_length=100, default='')  # name of artist
    title = models.CharField(max_length=100, default='')  # title of album
    genre = models.CharField(max_length=50, default='')  # genre of album
    logo = models.FileField(upload_to='uploads/')  # album logo
    year = models.CharField(max_length=4, default='')  # album year
    record_label = models.CharField(max_length=100, default='')  # record label

    def get_absolute_url(self):  # return details page of album after creating.
        return reverse('music:retrieve', kwargs={'pk': self.pk})

    def __str__(self):
        return 'Artist: ' + self.name + ' Album title: ' + self.title


class Song(models.Model):
    album = models.ForeignKey(Albums, on_delete=models.CASCADE)  # song album, on deletion delete all reference to song.
    format = models.CharField(max_length=10, default='')  # file type, i.e. mp4
    song_title = models.CharField(max_length=100, default='')  # song title
    duration = models.CharField(max_length=100, default='')  # song duration
    favorite = models.BooleanField(default=False)  # favorite the song

    def __str__(self):
        return self.song_title  # returning song title

music/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Albums, Song


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']

music/views.py
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from .models import Albums
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Albums.objects.all()


class RetrieveView(generic.DetailView):
    model = Albums
    template_name = 'music/retrieve.html'


class AlbumCreate(CreateView):
    model = Albums
    fields = ['name', 'title', 'genre', 'year', 'record_label', 'logo']
    template_name = 'music/album_form.html'


class AlbumUpdate(UpdateView):
    model = Albums
    fields = ['name', 'title', 'genre', 'year', 'record_label', 'logo']
    template_name = 'music/album_form.html'


class AlbumDelete(DeleteView):
    model = Albums
    success_url = reverse_lazy('music:index')
    fields = ['name', 'title', 'genre', 'year', 'record_label', 'logo']
    template_name = 'music/album_form.html'


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):  # display blank registration form
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):  # process the form
        form = self.form_class(request.POST)

        if form.is_valid():  # if the form is valid
            user = form.save(commit=False)  # stored locally

            username = form.cleaned_data['username']  # legitimize the data
            password = form.cleaned_data['password']
            user.set_password(password)  # set the password
            user.save()

            user = authenticate(username=username,
                                password=password)  # authenticate username and pass to see if they are in database

            if user is not None:

                if user.is_active:
                    login(request, user)  # user is now logged in
                    return redirect('music:index')  # redirect user to index page

            return render(request, self.template_name, {'form': form})  # send user back to blank form


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Albums.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DjWeb</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Modak&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <!--Header-->
    <a class="navbar-brand" href="{% url 'music:index' %}">DJWeb</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <!--Items-->
    <a href="{% url 'music:logout_user' %}"><i class="fas fa-sign-out-alt"></i></a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'music:index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:index' %}">Albums</a>
          <a class="nav-link" href="{% url 'music:index' %}">Songs</a>
        <a class="nav-link" href="{% url 'music:album-add' %}">Add Album</a>
          <a class="{% block login_active %}{% endblock %}" href="{% url 'music:login_user' %}">Log In</a>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>

</nav>
{% block body %}

{% endblock %}
</body>
</html>

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
<!-- Loads the path to your static files -->
{% extends 'music/base.html' %}
{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Albums</h3>
        </div>
        {% if object_list %}
            {% for Albums in object_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:retrieve' Albums.id %}">
                            <img src="{{ Albums.logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ Albums.title }}</h2>
                            <h4>{{ Albums.name }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:retrieve' Albums.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' Albums.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ Albums.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <i class="fas fa-plus-circle"></i>
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

music/templates/music/login.html
{% extends 'music/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
                            <h3>Create an account </h3>
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/retrieve.html
{% extends 'music/base.html' %}

{% block body %}
<img src="{{ Albums.logo.url }}">

<h1>{{ Albums.name }}</h1>
<h3>{{ Albums.title }}</h3>
<style>
    ul.a{
        list-style-type: circle;
    }

</style>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

    {% for Song in Albums.song_set.all %}
            {{ Song.song_title }}
            {% if Song.favorite %}
                <img src="https://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
        </label><br>
    {% endfor %}

{% endblock %}